package com.kaiharimoto.mastertool.core.port

import com.kaiharimoto.mastertool.core.board.DropIntent
import com.kaiharimoto.mastertool.core.board.FieldZone
import com.kaiharimoto.mastertool.core.board.CardPosition
import com.kaiharimoto.mastertool.core.board.MatPoint
import com.kaiharimoto.mastertool.core.board.PlayField
import com.kaiharimoto.mastertool.core.board.SetPosition
import com.kaiharimoto.mastertool.core.layout.BoardLayouter
import com.kaiharimoto.mastertool.core.model.CardId
import com.kaiharimoto.mastertool.core.layout.BoardSlot
import com.kaiharimoto.mastertool.core.motion.SpringSpec
import com.kaiharimoto.mastertool.core.motion.SpringValue
import com.kaiharimoto.mastertool.core.motion.Springs
import com.kaiharimoto.mastertool.core.ydk.YdkCodec
import kotlin.random.Random
import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Writes the golden vectors the 3DS port is held to.
 *
 * ## Why this is a test and not a tool
 *
 * `3ds/src/core/` is a hand-written C translation of the arithmetic in this
 * module. A translation nobody checks is a fork, and it drifts silently: the
 * tablet and the console would each be internally consistent and disagree about
 * where a card lands, which is the class of bug that takes a week to see.
 *
 * So the C is held to *this* module's output rather than to a second reading of
 * the same intent. This test sweeps each ported function over a fixed grid of
 * inputs and writes the answers to `3ds/test/vectors/`; `3ds/test/mt_test.c`
 * compiles the C on the host and asserts against the same file.
 *
 * ## The vectors are committed on purpose
 *
 * They are checked in, and CI runs `git diff --exit-code` over them after this
 * test. That makes the consequence visible in the only place it can be argued
 * about: a change to `BoardLayouter` that moves a zone shows up in review as a
 * diff in a vector file, next to the change that caused it. A regenerated
 * vector file is not a failure — it is the author being asked to notice that
 * the console's table just moved too, and to say so in the message.
 *
 * Nothing here asserts behaviour. `BoardLayoutTest` and the rest of commonTest
 * are where the rules are argued; this only records what they currently answer.
 */
class GoldenVectorExportTest {

    /**
     * Nine significant digits, because that is what round-trips an IEEE 754
     * single exactly. Fewer and the C would be asserted against a number the
     * Kotlin never produced, and the tolerance would have to absorb the
     * difference — which is the tolerance absorbing a bug.
     */
    private fun f(value: Float): String = String.format("%.9g", value)

    private fun b(value: Boolean): String = if (value) "1" else "0"

    /**
     * Walks up from the module directory to the repository root.
     *
     * The Gradle test working directory is the project dir (`app/core`), but
     * that is a default rather than a promise, and a hard `../../` would break
     * silently the day it changed — writing the vectors somewhere nobody looks
     * while still passing.
     */
    private fun vectorDir(): File {
        var dir: File? = File(".").absoluteFile
        while (dir != null) {
            val candidate = File(dir, "3ds/test/vectors")
            if (File(dir, "3ds").isDirectory) {
                candidate.mkdirs()
                return candidate
            }
            dir = dir.parentFile
        }
        error("no 3ds/ directory above ${File(".").absolutePath}")
    }

    private fun write(name: String, header: String, lines: List<String>) {
        val file = File(vectorDir(), name)
        file.writeText(
            buildString {
                appendLine("# generated by GoldenVectorExportTest - do not edit by hand")
                appendLine("# $header")
                lines.forEach { appendLine(it) }
            }
        )
        assertTrue(lines.isNotEmpty(), "$name would be empty, which asserts nothing")
    }

    @Test
    fun `board layout solve`() {
        // Both 3DS screens, both tablet ends of docs/DEVICES.md's matrix, and
        // the degenerate inputs the solver is documented to survive: a zero
        // width, an aspect ratio of zero, a growth below one and a roomAbove
        // past its own clamp.
        val widths = listOf(320f, 400f, 640f, 1480f, 0f)
        val heights = listOf(240f, 360f, 924f)
        val ratios = listOf(0.686f, 1f, 0f)
        val growths = listOf(1f, 1.35f, 0.5f)
        val rooms = listOf(0f, 0.2f, 0.9f)

        val lines = buildList {
            for (w in widths) for (h in heights) for (r in ratios)
                for (g in growths) for (room in rooms) {
                    val l = BoardLayouter.solve(w, h, r, g, room)
                    add(
                        listOf(
                            f(w), f(h), f(r), f(g), f(room), "=",
                            f(l.cardWidth), f(l.cardHeight), f(l.gap), b(l.fits),
                            f(l.field.left), f(l.field.top), f(l.field.width), f(l.field.height),
                            f(l.hand.left), f(l.hand.top), f(l.hand.width), f(l.hand.height),
                            f(l.readout.left), f(l.readout.top),
                            f(l.readout.width), f(l.readout.height),
                            f(l.bounds.left), f(l.bounds.top),
                            f(l.bounds.width), f(l.bounds.height),
                        ).joinToString(" ")
                    )
                }
        }
        write(
            "board_solve.txt",
            "w h ratio growth room = cardW cardH gap fits " +
                "fieldLTWH handLTWH readoutLTWH boundsLTWH",
            lines,
        )
    }

    /** The seventeen slots, in the insertion order `slotAt` resolves ties by. */
    @Test
    fun `board layout slots`() {
        val layout = BoardLayouter.solve(400f, 240f, 0.686f, 1f, 0f)
        val lines = layout.slots.entries.map { (slot, rect) ->
            "${slotName(slot)} = ${f(rect.left)} ${f(rect.top)} ${f(rect.width)} ${f(rect.height)}"
        }
        write("board_slots.txt", "slot = left top width height (INSERTION ORDER)", lines)
    }

    /**
     * `slotAt` over a grid finer than the gap between zones.
     *
     * The point is the midlines. Each slot claims half the gap around it, so
     * neighbours meet exactly on the boundary and the first in insertion order
     * takes it — which is a fact about a LinkedHashMap in Kotlin and about an
     * array index in C, and the only way to know those still agree is to ask
     * them both about a point that lands on one.
     */
    @Test
    fun `board layout slot at`() {
        val layout = BoardLayouter.solve(400f, 240f, 0.686f, 1f, 0f)
        val lines = buildList {
            var iy = 0
            while (iy <= 48) {
                var ix = 0
                while (ix <= 80) {
                    val x = ix * 5f
                    val y = iy * 5f
                    val hit = layout.slotAt(x, y)
                    add("${f(x)} ${f(y)} = ${hit?.let(::slotName) ?: "-"}")
                    ix++
                }
                iy++
            }
        }
        write("board_slot_at.txt", "x y = slot-or-dash (layout 400x240 r0.686 g1 room0)", lines)
    }

    @Test
    fun `set position`() {
        val zones: List<Pair<String, DropIntent?>> = listOf(
            "none" to null,
            "free" to DropIntent.Free(MatPoint(0.5f, 0.5f)),
            "monster" to DropIntent.Zone(BoardSlot.Zone(FieldZone.Monster(2)), MatPoint(0.5f, 0.5f)),
            "extra" to DropIntent.Zone(BoardSlot.Zone(FieldZone.ExtraMonster(0)), MatPoint(0.5f, 0.5f)),
            "spell" to DropIntent.Zone(BoardSlot.Zone(FieldZone.SpellTrap(1)), MatPoint(0.5f, 0.5f)),
            "field" to DropIntent.Zone(BoardSlot.Zone(FieldZone.FieldSpell), MatPoint(0.5f, 0.5f)),
            "deckslot" to DropIntent.Zone(BoardSlot.Deck, MatPoint(0.5f, 0.5f)),
            "stack" to DropIntent.Stack(7),
            "hand" to DropIntent.Hand(2),
            "graveyard" to DropIntent.Graveyard,
            "cancel" to DropIntent.Cancel,
        )
        val monsters: List<Pair<String, Boolean?>> =
            listOf("no" to false, "yes" to true, "unknown" to null)

        val lines = buildList {
            for (faceDown in listOf(false, true))
                for (turned in listOf(false, true))
                    for ((zoneName, intent) in zones)
                        for ((monsterName, monster) in monsters) {
                            val position = SetPosition.of(faceDown, turned, intent, monster)
                            add(
                                "${b(faceDown)} ${b(turned)} $zoneName $monsterName = ${position.name}"
                            )
                        }
        }
        write("set_position.txt", "faceDown turned intent monster = position", lines)
    }

    /**
     * Spring trajectories, stepped rather than sampled.
     *
     * A spring is not a function of its inputs, it is a function of its own
     * previous state, so a vector that checked one step would pass on an
     * integrator that had the order wrong. Semi-implicit Euler advances the
     * velocity first and the position with the *new* velocity; explicit Euler
     * uses the old one, injects energy, and diverges on a stiff spring. Those
     * two agree closely for one step and visibly disagree after forty, which is
     * why every step of every trajectory is written down.
     *
     * The dt list is deliberately awkward: a 60Hz frame, a 30Hz frame, one past
     * MAX_STEP so the clamp is exercised, and a zero.
     */
    @Test
    fun `spring trajectories`() {
        val specs = listOf(
            "snappy" to SpringSpec.Snappy,
            "bouncy" to SpringSpec.Bouncy,
            "calm" to SpringSpec.Calm,
        )
        val starts = listOf(0f to 0f, 120f to 0f, 40f to -900f)
        val targets = listOf(0f, 100f)
        val dts = listOf(1f / 60f, 1f / 30f, 0.25f, 0f)

        val lines = buildList {
            for ((specName, spec) in specs)
                for ((v0, vel0) in starts)
                    for (target in targets)
                        for (dt in dts) {
                            var state = SpringValue(v0, vel0)
                            for (i in 0 until 40) {
                                state = Springs.step(state, target, spec, dt)
                                add(
                                    "$specName ${f(v0)} ${f(vel0)} ${f(target)} ${f(dt)} $i " +
                                        "= ${f(state.value)} ${f(state.velocity)} " +
                                        b(Springs.settled(state, target))
                                )
                            }
                        }
        }
        write(
            "spring.txt",
            "spec v0 vel0 target dt step = value velocity settled",
            lines,
        )
    }

    /**
     * Deck files, parsed by both sides from byte-identical inputs.
     *
     * The synthetic cases are *written out as real files* rather than described,
     * so that the C reads exactly what the Kotlin read. A vector that quoted an
     * input inside itself would need two escapings to agree, and the first
     * disagreement between them would look like a parser bug.
     *
     * They are the awkward ones on purpose: a CRLF file, a UTF-8 BOM, a file
     * with no section marker at all, `!side` before `#extra`, junk lines, a
     * `#Created By` in the wrong case (which the Kotlin matches
     * case-insensitively and then strips case-*sensitively*, keeping the whole
     * string - a quirk the port reproduces rather than corrects), and a
     * `#ydkx-extended` block that is not readable and must be dropped.
     */
    @Test
    fun `ydk documents`() {
        val dir = File(vectorDir(), "case")
        dir.mkdirs()

        val cases = linkedMapOf(
            "plain.ydk" to "#main\n46986414\n46986414\n#extra\n#side\n",
            "crlf.ydk" to "#main\r\n46986414\r\n89631139\r\n!side\r\n38033121\r\n",
            "bom.ydk" to "\uFEFF#main\n46986414\n",
            "no-marker.ydk" to "46986414\n89631139\n",
            "side-first.ydk" to "#main\n46986414\n!side\n38033121\n#extra\n1861629\n",
            "junk.ydk" to "#main\n46986414\nnot-a-card\n  \n12x34\n89631139\n",
            "created-wrong-case.ydk" to "#Created By kai\n#main\n46986414\n",
            "created-lower.ydk" to "#created by kai\n#main\n46986414\n",
            "comment.ydk" to "#this is a comment\n#main\n46986414\n",
            "negative.ydk" to "#main\n-46986414\n46986414\n",
            "huge-id.ydk" to "#main\n999999999999\n46986414\n",
            "ydkx-good.ydkx" to
                "#main\n46986414\n#ydkx-extended\n{\"groups\":[{\"name\":\"Starters\"}],\"notes\":{}}\n",
            "ydkx-broken.ydkx" to "#main\n46986414\n#ydkx-extended\n{\"groups\": [\n",
            "ydkx-empty.ydkx" to "#main\n46986414\n#ydkx-extended\n",
        )
        cases.forEach { (name, body) -> File(dir, name).writeText(body) }

        // The real ones too. A synthetic suite proves the edge cases; a deck
        // somebody actually built proves the ordinary case, which is the one
        // that has to work on the console.
        // Labelled by where they came from, not by their file name. The
        // repository holds *two different decks* both called lab.ydkx - one at
        // the root and one in ydk/ - so a label of `it.name` silently gave two
        // inputs the same key, and the conformance suite read the first file
        // twice while comparing it against the second file's answers.
        val repo = vectorDir().parentFile.parentFile.parentFile
        val real = buildList {
            add(File(repo, "lab.ydkx"))
            File(repo, "ydk").listFiles()?.sortedBy { it.name }?.let(::addAll)
        }

        val entries = cases.keys.map { "case/$it" to File(dir, it) } +
            real.filter { it.isFile }.map { "repo/${it.relativeTo(repo).invariantSeparatorsPath}" to it }

        val lines = buildList {
            for ((label, file) in entries) {
                val result = YdkCodec.parse(file.readText())
                val doc = result.document
                add("$label ydkx ${b(doc.isYdkx)}")
                add("$label warnings ${result.warnings.size}")
                add("$label main ${doc.deck.main.size} ${doc.deck.main.joinToString(" ") { it.value.toString() }}".trim())
                add("$label extra ${doc.deck.extra.size} ${doc.deck.extra.joinToString(" ") { it.value.toString() }}".trim())
                add("$label side ${doc.deck.side.size} ${doc.deck.side.joinToString(" ") { it.value.toString() }}".trim())
                // Last, and taking the rest of the line, because a name may
                // contain spaces and this format splits on them.
                add("$label created ${doc.createdBy ?: "-"}")
            }
        }
        write("ydk.txt", "<file> <key> <values...>  (case/* live in vectors/case/, repo/* at the repo root)", lines)
    }

    /**
     * The generator itself, before anything that uses it.
     *
     * `PlayField.riffled` writes Fisher-Yates out by hand instead of calling
     * `shuffled(Random(seed))`, and its comment says why: the standard library
     * may change its algorithm between versions and platforms, and a seed that
     * dealt one hand on a tablet and another on a desktop would make every bug
     * report about an opening hand unreproducible.
     *
     * That reasoning does not survive a port unless the *generator* crosses over
     * with it. An identical Fisher-Yates fed by a different PRNG is a shuffle
     * that is correct, deterministic and a different deal — the very failure the
     * hand-written loop exists to prevent, walking in through the one door it
     * left open. So `kotlin.random.Random` — XorWow, not `java.util.Random` — is
     * reproduced in C, and this is what holds it there.
     *
     * The bounds are chosen to hit both branches of `nextInt(until)`: powers of
     * two take the upper bits directly, everything else goes through a modulo
     * with a rejection loop for the short tail.
     */
    @Test
    fun `kotlin random`() {
        val seeds = listOf(0L, 1L, 7L, 42L, -1L, 1234567890123L, Long.MIN_VALUE, Long.MAX_VALUE)
        val bounds = listOf(2, 3, 5, 8, 16, 17, 40, 60, 1000, 65536)

        val lines = buildList {
            for (seed in seeds) {
                // The raw stream first, which pins seeding and the 64 discarded
                // outputs independently of any bound arithmetic.
                val raw = Random(seed)
                for (i in 0 until 24) add("raw $seed $i = ${raw.nextInt()}")

                for (bound in bounds) {
                    val random = Random(seed)
                    for (i in 0 until 16) {
                        add("bound $seed $bound $i = ${random.nextInt(bound)}")
                    }
                }
            }
        }
        write("random.txt", "raw <seed> <i> = <int>  |  bound <seed> <bound> <i> = <int>", lines)
    }

    /**
     * The table itself, driven by a script that lives in the vector file.
     *
     * `PlayField` is the one ported thing that is *stateful*, and that changes
     * what a vector has to be. A function can be swept over a grid of inputs; a
     * table has to be walked, because each operation's correctness depends on
     * every operation before it.
     *
     * So the script is written **into the file** rather than duplicated in both
     * languages, and it is built **as it runs**, against the live field. The
     * first version of this test hardcoded instance ids, and after a shuffle
     * those ids are somewhere else — so `stack`, `attach`, `counter` and
     * `takeFromUnder` were all quietly *refused*, the suite recorded the
     * refusals faithfully on both sides, and 25,945 checks passed without ever
     * executing the code they were written for. Two deliberate mutations went
     * undetected before that was noticed.
     *
     * Refusals still matter and are still recorded — `ok 0` is a real answer,
     * and the state after one is compared too, because the Kotlin gets "the
     * field is unchanged" free from immutability and the C has to earn it. But
     * a refusal has to be *chosen*, not stumbled into.
     */
    @Test
    fun `play field script`() {
        // Distinct passcodes, so a card in the wrong pile is visible rather
        // than plausible.
        val main = (1..24).map { CardId(1000 + it) }
        val extra = (1..6).map { CardId(9000 + it) }

        var field = PlayField.setUp(main, extra)
        val lines = mutableListOf<String>()
        var step = 0

        fun position(raw: Int): CardPosition? =
            if (raw >= CardPosition.entries.size) null else CardPosition.entries[raw]

        fun record(ok: Boolean) {
            lines += "$step ok ${b(ok)}"
            lines += "$step lp ${field.lifePoints} phase ${field.phase.ordinal} turn ${field.turn}"
            lines += "$step mat ${field.mat.size}"
            field.mat.forEachIndexed { i, placed ->
                val sb = StringBuilder("$step mat$i ${placed.id} ${placed.card.cardId.value} ")
                sb.append("${f(placed.at.x)} ${f(placed.at.y)} ")
                sb.append("${placed.card.position.ordinal} ${placed.card.counters} ")
                sb.append("${placed.beneath.size}")
                placed.beneath.forEach { sb.append(" ${it.instanceId}") }
                sb.append(" ${placed.card.materials.size}")
                placed.card.materials.forEach { sb.append(" ${it.instanceId}") }
                lines += sb.toString()
            }
            // Position and counters travel with a card into a pile, and used to
            // be dropped here — which made `lift` clearing counters and
            // `toBanish` setting face-down both invisible. A mutation that left
            // counters on a card sent to the graveyard passed cleanly.
            fun pile(name: String, cards: List<com.kaiharimoto.mastertool.core.board.BoardCard>) {
                lines += "$step $name ${cards.size}" + cards.joinToString("") {
                    " ${it.instanceId} ${it.position.ordinal} ${it.counters}"
                }
            }
            pile("hand", field.hand)
            pile("deck", field.deck)
            pile("extra", field.extraDeck)
            pile("gy", field.graveyard)
            pile("ban", field.banished)
        }

        fun run(raw: String) {
            step += 1
            val parts = raw.trim().split(" ")
            val op = parts[0]
            fun i(n: Int) = parts[n].toInt()
            fun p(n: Int) = parts[n].toFloat()
            fun at(n: Int) = MatPoint(p(n), p(n + 1))

            val next: PlayField? = when (op) {
                "shuffle" -> field.shuffleDeck(parts[1].toLong())
                "draw" -> field.draw()
                "playhand" -> field.playFromHand(i(1), at(2), CardPosition.entries[i(4)])
                "playdeck" -> field.playFromDeck(i(1), at(2), CardPosition.entries[i(4)])
                "playextra" -> field.playFromExtra(i(1), at(2), CardPosition.entries[i(4)])
                "playgy" -> field.playFromGraveyard(i(1), at(2), CardPosition.entries[i(4)])
                "playban" -> field.playFromBanished(i(1), at(2), CardPosition.entries[i(4)])
                "move" -> field.moveOnMat(i(1), at(2), position(i(4)))
                "stack" -> field.stackOnto(i(1), i(2), position(i(3)))
                "unstack" -> field.unstack(i(1), at(2))
                "front" -> field.bringToFront(i(1))
                "flip" -> field.flip(i(1))
                "rotate" -> field.rotate(i(1))
                "setpos" -> field.setPosition(i(1), CardPosition.entries[i(2)])
                "gy" -> field.toGraveyard(i(1))
                "banish" -> field.toBanish(i(1), i(2) != 0)
                "tohand" -> field.toHand(i(1), i(2).takeIf { it >= 0 })
                "decktop" -> field.toDeckTop(i(1))
                "deckbottom" -> field.toDeckBottom(i(1))
                "toextra" -> field.toExtraDeck(i(1))
                "handgy" -> field.handToGraveyard(i(1))
                "handbanish" -> field.handToBanish(i(1))
                "handdecktop" -> field.handToDeckTop(i(1))
                "handdeckbottom" -> field.handToDeckBottom(i(1))
                "reorder" -> field.reorderHand(i(1), i(2))
                "counter" -> field.addCounter(i(1), i(2))
                "attach" -> field.attachAsMaterial(i(1), i(2))
                "detach" -> field.detachMaterial(i(1))
                // The position is ignored when the index is 0 — that path is a
                // plain slide of the top card — which is exactly the asymmetry
                // the C has to reproduce rather than tidy away.
                "takefromunder" -> field.takeFromUnder(i(1), i(2), at(3), CardPosition.entries[i(5)])
                "life" -> field.adjustLifePoints(i(1))
                "phase" -> field.nextPhase()
                "endturn" -> field.endTurn()
                else -> error("unknown op '$op'")
            }

            lines += "$step op $raw"
            if (next != null) field = next
            record(next != null)
        }

        /** The instance on the mat at [index] from the back, so ops name real cards. */
        fun onMat(index: Int) = field.mat[index].id
        fun top() = field.mat.last().id

        record(true)   // step 0

        run("shuffle 20260820")
        repeat(6) { run("draw") }

        // Four cards down, so there is something to build piles out of.
        run("playhand 0 0.30 0.40 0")
        run("playhand 0 0.50 0.40 2")
        run("playhand 0 0.70 0.40 1")
        run("playhand 0 0.20 0.60 0")

        val a = onMat(0); val bCard = onMat(1); val c = onMat(2); val d = onMat(3)

        run("move $a 0.32 0.45 4")          // 4 == keep
        run("move $bCard 0.50 0.42 0")
        run("front $a")
        run("front ${top()}")               // already there: refused
        run("flip $bCard")
        run("rotate $a")
        run("setpos $c 3")

        // Two piles of two, then one pile onto the other — the only shape that
        // exercises the order `beneath` is concatenated in.
        run("stack $a $bCard 4")
        run("stack $c $d 4")
        run("stack $a $c 4")
        run("stack $a $a 4")                // onto itself: refused

        run("counter $a 3")
        run("takefromunder $a 2 0.15 0.55 0")
        run("takefromunder $a 0 0.16 0.56 2")   // index 0 ignores the position
        run("unstack $a 0.20 0.20")

        run("playdeck 0 0.10 0.10 0")
        run("playdeck 99 0.10 0.10 0")      // out of range: refused
        run("playextra 0 0.90 0.10 1")

        val host = top()
        val guest = onMat(0)
        run("attach $guest $host")
        run("attach $host $host")           // onto itself: refused
        run("detach $host")
        run("detach $host")                 // nothing attached now: refused

        // A card with counters leaving the mat, so `lift` clearing them is seen.
        run("counter $host 4")
        run("gy $host")

        run("banish ${top()} 1")            // face-down, which the pile must show
        run("tohand ${top()} 0")
        run("decktop ${top()}")
        if (field.mat.isNotEmpty()) run("deckbottom ${top()}")
        if (field.mat.isNotEmpty()) run("toextra ${top()}")

        // Enough cards in hand that reordering has somewhere to go. Without
        // this the hand held one card by now, `ints_insert_at` clamped both
        // branches of reorderHand's `to > from` adjustment to the same place,
        // and a mutation deleting that adjustment passed cleanly.
        repeat(5) { run("draw") }
        run("reorder 0 3")
        run("reorder 3 0")
        run("reorder 1 4")
        run("reorder 4 2")

        run("handgy 0")
        run("handbanish 0")
        run("handdecktop 0")
        run("handdeckbottom 0")
        run("reorder 0 2")
        run("reorder 1 1")                  // its own place: refused
        run("reorder 1 2")                  // the gap after itself: refused

        run("playgy 0 0.40 0.80 0")
        run("playban 0 0.60 0.80 0")
        run("counter ${top()} -99")         // clamps to zero
        run("counter ${top()} 0")           // no change: refused

        run("life -1200")
        run("life -99999")                  // clamps to zero
        run("phase"); run("phase"); run("endturn")
        run("shuffle -7")

        write("playfield.txt", "<step> op <script line> then the whole field, keyed by step", lines)
    }

    /** The stable spelling of a slot, shared with the C by convention. */
    private fun slotName(slot: BoardSlot): String = when (slot) {
        is BoardSlot.Zone -> when (val z = slot.zone) {
            is FieldZone.Monster -> "M${z.index}"
            is FieldZone.ExtraMonster -> "E${z.index}"
            is FieldZone.SpellTrap -> "S${z.index}"
            FieldZone.FieldSpell -> "F"
        }
        BoardSlot.Deck -> "DECK"
        BoardSlot.ExtraDeck -> "EXTRA"
        BoardSlot.Graveyard -> "GY"
        BoardSlot.Banished -> "BAN"
    }
}
