package com.kaiharimoto.mastertool.core.port

import com.kaiharimoto.mastertool.core.board.DropIntent
import com.kaiharimoto.mastertool.core.board.FieldZone
import com.kaiharimoto.mastertool.core.board.MatPoint
import com.kaiharimoto.mastertool.core.board.SetPosition
import com.kaiharimoto.mastertool.core.layout.BoardLayouter
import com.kaiharimoto.mastertool.core.layout.BoardSlot
import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Writes the golden vectors the 3DS port is held to.
 *
 * ## Why this is a test and not a tool
 *
 * `3ds/src/core/` is a hand-written C translation of the arithmetic in this
 * module. A translation nobody checks is a fork, and it drifts silently: the
 * tablet and the console would each be internally consistent and disagree about
 * where a card lands, which is the class of bug that takes a week to see.
 *
 * So the C is held to *this* module's output rather than to a second reading of
 * the same intent. This test sweeps each ported function over a fixed grid of
 * inputs and writes the answers to `3ds/test/vectors/`; `3ds/test/mt_test.c`
 * compiles the C on the host and asserts against the same file.
 *
 * ## The vectors are committed on purpose
 *
 * They are checked in, and CI runs `git diff --exit-code` over them after this
 * test. That makes the consequence visible in the only place it can be argued
 * about: a change to `BoardLayouter` that moves a zone shows up in review as a
 * diff in a vector file, next to the change that caused it. A regenerated
 * vector file is not a failure — it is the author being asked to notice that
 * the console's table just moved too, and to say so in the message.
 *
 * Nothing here asserts behaviour. `BoardLayoutTest` and the rest of commonTest
 * are where the rules are argued; this only records what they currently answer.
 */
class GoldenVectorExportTest {

    /**
     * Nine significant digits, because that is what round-trips an IEEE 754
     * single exactly. Fewer and the C would be asserted against a number the
     * Kotlin never produced, and the tolerance would have to absorb the
     * difference — which is the tolerance absorbing a bug.
     */
    private fun f(value: Float): String = String.format("%.9g", value)

    private fun b(value: Boolean): String = if (value) "1" else "0"

    /**
     * Walks up from the module directory to the repository root.
     *
     * The Gradle test working directory is the project dir (`app/core`), but
     * that is a default rather than a promise, and a hard `../../` would break
     * silently the day it changed — writing the vectors somewhere nobody looks
     * while still passing.
     */
    private fun vectorDir(): File {
        var dir: File? = File(".").absoluteFile
        while (dir != null) {
            val candidate = File(dir, "3ds/test/vectors")
            if (File(dir, "3ds").isDirectory) {
                candidate.mkdirs()
                return candidate
            }
            dir = dir.parentFile
        }
        error("no 3ds/ directory above ${File(".").absolutePath}")
    }

    private fun write(name: String, header: String, lines: List<String>) {
        val file = File(vectorDir(), name)
        file.writeText(
            buildString {
                appendLine("# generated by GoldenVectorExportTest - do not edit by hand")
                appendLine("# $header")
                lines.forEach { appendLine(it) }
            }
        )
        assertTrue(lines.isNotEmpty(), "$name would be empty, which asserts nothing")
    }

    @Test
    fun `board layout solve`() {
        // Both 3DS screens, both tablet ends of docs/DEVICES.md's matrix, and
        // the degenerate inputs the solver is documented to survive: a zero
        // width, an aspect ratio of zero, a growth below one and a roomAbove
        // past its own clamp.
        val widths = listOf(320f, 400f, 640f, 1480f, 0f)
        val heights = listOf(240f, 360f, 924f)
        val ratios = listOf(0.686f, 1f, 0f)
        val growths = listOf(1f, 1.35f, 0.5f)
        val rooms = listOf(0f, 0.2f, 0.9f)

        val lines = buildList {
            for (w in widths) for (h in heights) for (r in ratios)
                for (g in growths) for (room in rooms) {
                    val l = BoardLayouter.solve(w, h, r, g, room)
                    add(
                        listOf(
                            f(w), f(h), f(r), f(g), f(room), "=",
                            f(l.cardWidth), f(l.cardHeight), f(l.gap), b(l.fits),
                            f(l.field.left), f(l.field.top), f(l.field.width), f(l.field.height),
                            f(l.hand.left), f(l.hand.top), f(l.hand.width), f(l.hand.height),
                            f(l.readout.left), f(l.readout.top),
                            f(l.readout.width), f(l.readout.height),
                            f(l.bounds.left), f(l.bounds.top),
                            f(l.bounds.width), f(l.bounds.height),
                        ).joinToString(" ")
                    )
                }
        }
        write(
            "board_solve.txt",
            "w h ratio growth room = cardW cardH gap fits " +
                "fieldLTWH handLTWH readoutLTWH boundsLTWH",
            lines,
        )
    }

    /** The seventeen slots, in the insertion order `slotAt` resolves ties by. */
    @Test
    fun `board layout slots`() {
        val layout = BoardLayouter.solve(400f, 240f, 0.686f, 1f, 0f)
        val lines = layout.slots.entries.map { (slot, rect) ->
            "${slotName(slot)} = ${f(rect.left)} ${f(rect.top)} ${f(rect.width)} ${f(rect.height)}"
        }
        write("board_slots.txt", "slot = left top width height (INSERTION ORDER)", lines)
    }

    /**
     * `slotAt` over a grid finer than the gap between zones.
     *
     * The point is the midlines. Each slot claims half the gap around it, so
     * neighbours meet exactly on the boundary and the first in insertion order
     * takes it — which is a fact about a LinkedHashMap in Kotlin and about an
     * array index in C, and the only way to know those still agree is to ask
     * them both about a point that lands on one.
     */
    @Test
    fun `board layout slot at`() {
        val layout = BoardLayouter.solve(400f, 240f, 0.686f, 1f, 0f)
        val lines = buildList {
            var iy = 0
            while (iy <= 48) {
                var ix = 0
                while (ix <= 80) {
                    val x = ix * 5f
                    val y = iy * 5f
                    val hit = layout.slotAt(x, y)
                    add("${f(x)} ${f(y)} = ${hit?.let(::slotName) ?: "-"}")
                    ix++
                }
                iy++
            }
        }
        write("board_slot_at.txt", "x y = slot-or-dash (layout 400x240 r0.686 g1 room0)", lines)
    }

    @Test
    fun `set position`() {
        val zones: List<Pair<String, DropIntent?>> = listOf(
            "none" to null,
            "free" to DropIntent.Free(MatPoint(0.5f, 0.5f)),
            "monster" to DropIntent.Zone(BoardSlot.Zone(FieldZone.Monster(2)), MatPoint(0.5f, 0.5f)),
            "extra" to DropIntent.Zone(BoardSlot.Zone(FieldZone.ExtraMonster(0)), MatPoint(0.5f, 0.5f)),
            "spell" to DropIntent.Zone(BoardSlot.Zone(FieldZone.SpellTrap(1)), MatPoint(0.5f, 0.5f)),
            "field" to DropIntent.Zone(BoardSlot.Zone(FieldZone.FieldSpell), MatPoint(0.5f, 0.5f)),
            "deckslot" to DropIntent.Zone(BoardSlot.Deck, MatPoint(0.5f, 0.5f)),
            "stack" to DropIntent.Stack(7),
            "hand" to DropIntent.Hand(2),
            "graveyard" to DropIntent.Graveyard,
            "cancel" to DropIntent.Cancel,
        )
        val monsters: List<Pair<String, Boolean?>> =
            listOf("no" to false, "yes" to true, "unknown" to null)

        val lines = buildList {
            for (faceDown in listOf(false, true))
                for (turned in listOf(false, true))
                    for ((zoneName, intent) in zones)
                        for ((monsterName, monster) in monsters) {
                            val position = SetPosition.of(faceDown, turned, intent, monster)
                            add(
                                "${b(faceDown)} ${b(turned)} $zoneName $monsterName = ${position.name}"
                            )
                        }
        }
        write("set_position.txt", "faceDown turned intent monster = position", lines)
    }

    /** The stable spelling of a slot, shared with the C by convention. */
    private fun slotName(slot: BoardSlot): String = when (slot) {
        is BoardSlot.Zone -> when (val z = slot.zone) {
            is FieldZone.Monster -> "M${z.index}"
            is FieldZone.ExtraMonster -> "E${z.index}"
            is FieldZone.SpellTrap -> "S${z.index}"
            FieldZone.FieldSpell -> "F"
        }
        BoardSlot.Deck -> "DECK"
        BoardSlot.ExtraDeck -> "EXTRA"
        BoardSlot.Graveyard -> "GY"
        BoardSlot.Banished -> "BAN"
    }
}
